language: node_js
node_js:
- 7.2.0
branches:
  only:
  - dev

install:
- npm install -g hexo-cli
- npm install

before_script:
- git config --global user.name "ileenhow"
- git config --global user.email "ileenhow@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build
